// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// CorTree_sampler
Rcpp::List CorTree_sampler(arma::mat X, int n_clus, int tree_depth, int cutoff_layer, int total_iter, int burnin, int warm_start, arma::uvec init_Z, double c_sigma2_vec, double sigma_mu2, bool all_ind, int cov_interval, bool save_phi_trace, bool save_cluster_cor_trace, double z_det_gamma0, int z_mode, bool z_det_gamma_linear);
RcppExport SEXP _CorTree_CorTree_sampler(SEXP XSEXP, SEXP n_clusSEXP, SEXP tree_depthSEXP, SEXP cutoff_layerSEXP, SEXP total_iterSEXP, SEXP burninSEXP, SEXP warm_startSEXP, SEXP init_ZSEXP, SEXP c_sigma2_vecSEXP, SEXP sigma_mu2SEXP, SEXP all_indSEXP, SEXP cov_intervalSEXP, SEXP save_phi_traceSEXP, SEXP save_cluster_cor_traceSEXP, SEXP z_det_gamma0SEXP, SEXP z_modeSEXP, SEXP z_det_gamma_linearSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type n_clus(n_clusSEXP);
    Rcpp::traits::input_parameter< int >::type tree_depth(tree_depthSEXP);
    Rcpp::traits::input_parameter< int >::type cutoff_layer(cutoff_layerSEXP);
    Rcpp::traits::input_parameter< int >::type total_iter(total_iterSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type warm_start(warm_startSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type init_Z(init_ZSEXP);
    Rcpp::traits::input_parameter< double >::type c_sigma2_vec(c_sigma2_vecSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_mu2(sigma_mu2SEXP);
    Rcpp::traits::input_parameter< bool >::type all_ind(all_indSEXP);
    Rcpp::traits::input_parameter< int >::type cov_interval(cov_intervalSEXP);
    Rcpp::traits::input_parameter< bool >::type save_phi_trace(save_phi_traceSEXP);
    Rcpp::traits::input_parameter< bool >::type save_cluster_cor_trace(save_cluster_cor_traceSEXP);
    Rcpp::traits::input_parameter< double >::type z_det_gamma0(z_det_gamma0SEXP);
    Rcpp::traits::input_parameter< int >::type z_mode(z_modeSEXP);
    Rcpp::traits::input_parameter< bool >::type z_det_gamma_linear(z_det_gamma_linearSEXP);
    rcpp_result_gen = Rcpp::wrap(CorTree_sampler(X, n_clus, tree_depth, cutoff_layer, total_iter, burnin, warm_start, init_Z, c_sigma2_vec, sigma_mu2, all_ind, cov_interval, save_phi_trace, save_cluster_cor_trace, z_det_gamma0, z_mode, z_det_gamma_linear));
    return rcpp_result_gen;
END_RCPP
}
// CorTree_heldout_logpred
Rcpp::List CorTree_heldout_logpred(const arma::mat& X_test, const Rcpp::List& mcmc, int tree_depth, int cutoff_layer, int burnin, bool all_ind, int n_phi_mc);
RcppExport SEXP _CorTree_CorTree_heldout_logpred(SEXP X_testSEXP, SEXP mcmcSEXP, SEXP tree_depthSEXP, SEXP cutoff_layerSEXP, SEXP burninSEXP, SEXP all_indSEXP, SEXP n_phi_mcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_test(X_testSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type mcmc(mcmcSEXP);
    Rcpp::traits::input_parameter< int >::type tree_depth(tree_depthSEXP);
    Rcpp::traits::input_parameter< int >::type cutoff_layer(cutoff_layerSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< bool >::type all_ind(all_indSEXP);
    Rcpp::traits::input_parameter< int >::type n_phi_mc(n_phi_mcSEXP);
    rcpp_result_gen = Rcpp::wrap(CorTree_heldout_logpred(X_test, mcmc, tree_depth, cutoff_layer, burnin, all_ind, n_phi_mc));
    return rcpp_result_gen;
END_RCPP
}
// CorTree_heldout_membership
Rcpp::List CorTree_heldout_membership(const arma::mat& X_test, const Rcpp::List& mcmc, int tree_depth, int cutoff_layer, int burnin, bool all_ind, int n_phi_mc);
RcppExport SEXP _CorTree_CorTree_heldout_membership(SEXP X_testSEXP, SEXP mcmcSEXP, SEXP tree_depthSEXP, SEXP cutoff_layerSEXP, SEXP burninSEXP, SEXP all_indSEXP, SEXP n_phi_mcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_test(X_testSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type mcmc(mcmcSEXP);
    Rcpp::traits::input_parameter< int >::type tree_depth(tree_depthSEXP);
    Rcpp::traits::input_parameter< int >::type cutoff_layer(cutoff_layerSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< bool >::type all_ind(all_indSEXP);
    Rcpp::traits::input_parameter< int >::type n_phi_mc(n_phi_mcSEXP);
    rcpp_result_gen = Rcpp::wrap(CorTree_heldout_membership(X_test, mcmc, tree_depth, cutoff_layer, burnin, all_ind, n_phi_mc));
    return rcpp_result_gen;
END_RCPP
}
// aggregate_tree_counts
Rcpp::List aggregate_tree_counts(arma::mat count_data, Rcpp::List tree);
RcppExport SEXP _CorTree_aggregate_tree_counts(SEXP count_dataSEXP, SEXP treeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type count_data(count_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type tree(treeSEXP);
    rcpp_result_gen = Rcpp::wrap(aggregate_tree_counts(count_data, tree));
    return rcpp_result_gen;
END_RCPP
}
// isIn
arma::uvec isIn(const arma::uvec& a, const arma::uvec& b);
RcppExport SEXP _CorTree_isIn(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uvec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(isIn(a, b));
    return rcpp_result_gen;
END_RCPP
}
// complementarySet
arma::uvec complementarySet(const arma::uvec& a, const arma::uvec& b);
RcppExport SEXP _CorTree_complementarySet(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uvec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(complementarySet(a, b));
    return rcpp_result_gen;
END_RCPP
}
// PhyloTree_sampler
Rcpp::List PhyloTree_sampler(arma::mat count_data, Rcpp::List tree, int n_clus, int cutoff_layer, int total_iter, int burnin, int warm_start, arma::uvec init_Z, double c_sigma2_vec, double sigma_mu2, bool all_ind, int cov_interval);
RcppExport SEXP _CorTree_PhyloTree_sampler(SEXP count_dataSEXP, SEXP treeSEXP, SEXP n_clusSEXP, SEXP cutoff_layerSEXP, SEXP total_iterSEXP, SEXP burninSEXP, SEXP warm_startSEXP, SEXP init_ZSEXP, SEXP c_sigma2_vecSEXP, SEXP sigma_mu2SEXP, SEXP all_indSEXP, SEXP cov_intervalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type count_data(count_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< int >::type n_clus(n_clusSEXP);
    Rcpp::traits::input_parameter< int >::type cutoff_layer(cutoff_layerSEXP);
    Rcpp::traits::input_parameter< int >::type total_iter(total_iterSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type warm_start(warm_startSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type init_Z(init_ZSEXP);
    Rcpp::traits::input_parameter< double >::type c_sigma2_vec(c_sigma2_vecSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_mu2(sigma_mu2SEXP);
    Rcpp::traits::input_parameter< bool >::type all_ind(all_indSEXP);
    Rcpp::traits::input_parameter< int >::type cov_interval(cov_intervalSEXP);
    rcpp_result_gen = Rcpp::wrap(PhyloTree_sampler(count_data, tree, n_clus, cutoff_layer, total_iter, burnin, warm_start, init_Z, c_sigma2_vec, sigma_mu2, all_ind, cov_interval));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_pgdraw
NumericVector rcpp_pgdraw(NumericVector b, NumericVector c);
RcppExport SEXP _CorTree_rcpp_pgdraw(SEXP bSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_pgdraw(b, c));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CorTree_CorTree_sampler", (DL_FUNC) &_CorTree_CorTree_sampler, 17},
    {"_CorTree_CorTree_heldout_logpred", (DL_FUNC) &_CorTree_CorTree_heldout_logpred, 7},
    {"_CorTree_CorTree_heldout_membership", (DL_FUNC) &_CorTree_CorTree_heldout_membership, 7},
    {"_CorTree_aggregate_tree_counts", (DL_FUNC) &_CorTree_aggregate_tree_counts, 2},
    {"_CorTree_isIn", (DL_FUNC) &_CorTree_isIn, 2},
    {"_CorTree_complementarySet", (DL_FUNC) &_CorTree_complementarySet, 2},
    {"_CorTree_PhyloTree_sampler", (DL_FUNC) &_CorTree_PhyloTree_sampler, 12},
    {"_CorTree_rcpp_pgdraw", (DL_FUNC) &_CorTree_rcpp_pgdraw, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_CorTree(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
