# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CorTree_sampler <- function(X, n_clus, tree_depth, cutoff_layer, total_iter, burnin, warm_start = 0L, init_Z, c_sigma2_vec = 1.0, sigma_mu2 = 1.0, all_ind = FALSE, cov_interval = 1L, save_phi_trace = FALSE, save_cluster_cor_trace = FALSE, z_det_gamma0 = 1.0, z_mode = 0L, z_det_gamma_linear = FALSE) {
    .Call(`_CorTree_CorTree_sampler`, X, n_clus, tree_depth, cutoff_layer, total_iter, burnin, warm_start, init_Z, c_sigma2_vec, sigma_mu2, all_ind, cov_interval, save_phi_trace, save_cluster_cor_trace, z_det_gamma0, z_mode, z_det_gamma_linear)
}

CorTree_heldout_logpred <- function(X_test, mcmc, tree_depth, cutoff_layer, burnin = 0L, all_ind = FALSE, n_phi_mc = 1L) {
    .Call(`_CorTree_CorTree_heldout_logpred`, X_test, mcmc, tree_depth, cutoff_layer, burnin, all_ind, n_phi_mc)
}

CorTree_heldout_membership <- function(X_test, mcmc, tree_depth, cutoff_layer, burnin = 0L, all_ind = FALSE, n_phi_mc = 1L) {
    .Call(`_CorTree_CorTree_heldout_membership`, X_test, mcmc, tree_depth, cutoff_layer, burnin, all_ind, n_phi_mc)
}

#' Aggregate counts along a phylogenetic tree and output node depths
NULL

aggregate_tree_counts <- function(count_data, tree) {
    .Call(`_CorTree_aggregate_tree_counts`, count_data, tree)
}

isIn <- function(a, b) {
    .Call(`_CorTree_isIn`, a, b)
}

complementarySet <- function(a, b) {
    .Call(`_CorTree_complementarySet`, a, b)
}

PhyloTree_sampler <- function(count_data, tree, n_clus, cutoff_layer, total_iter, burnin, warm_start = 0L, init_Z, c_sigma2_vec = 1.0, sigma_mu2 = 1.0, all_ind = FALSE, cov_interval = 1L, save_phi_trace = FALSE, save_sigma_inv_trace = FALSE, save_cluster_cor_trace = FALSE) {
    .Call(`_CorTree_PhyloTree_sampler`, count_data, tree, n_clus, cutoff_layer, total_iter, burnin, warm_start, init_Z, c_sigma2_vec, sigma_mu2, all_ind, cov_interval, save_phi_trace, save_sigma_inv_trace, save_cluster_cor_trace)
}

rcpp_pgdraw <- function(b, c) {
    .Call(`_CorTree_rcpp_pgdraw`, b, c)
}

