# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CorTree_sampler <- function(X, n_clus, tree_depth, cutoff_layer, total_iter, burnin, warm_start = 0L, init_Z, c_sigma2_vec = 1.0, sigma_mu2 = 1.0, all_ind = FALSE, cov_interval = 1L) {
    .Call('_CorTree_CorTree_sampler', PACKAGE = 'CorTree', X, n_clus, tree_depth, cutoff_layer, total_iter, burnin, warm_start, init_Z, c_sigma2_vec, sigma_mu2, all_ind, cov_interval)
}

rcpp_pgdraw <- function(b, c) {
    .Call('_CorTree_rcpp_pgdraw', PACKAGE = 'CorTree', b, c)
}

